import test from 'node:test';
import assert from 'node:assert/strict';
import {initial,sample,replace,combinations,multiplier,selectedMoves,profile,errors,analyze,validateParty,advicePayload} from '../.test-build/engine.mjs';
import {dex,byId,samples} from '../.test-build/data.mjs';
import {handleAdvice} from '../.test-build/advice.mjs';
test('미등장 패러독스 제외',()=>assert(!dex.some(p=>/Flutter Mane|Iron Valiant|날개치는머리|무쇠무인/.test(p.en+p.name))));
test('맘모꾸리와 메가팬텀 검색 데이터',()=>{assert.equal(byId.mamoswine.name,'맘모꾸리');assert.equal(byId['mega-gengar'].name,'메가팬텀');});
test('요청한 X Y Z 관측 폼 존재',()=>{for(const id of ['charizard','mega-charizard-x','mega-charizard-y','mega-lucario-z','mega-garchomp-z','mega-raichu-x','mega-raichu-y','mega-golisopod'])assert(byId[id],id);});
test('종 중복 차단',()=>assert.throws(()=>replace(initial(),5,'salamence'),/동일 종/));
test('고정 슬롯 보호',()=>{const p=initial();p.slots[0].locked=true;assert.throws(()=>replace(p,0,'garchomp'),/고정/);});
test('메가 없는 6→3은 20조합',()=>{const p=initial();p.slots[0]=sample('salamence');p.slots[1]=sample('golisopod');assert.equal(combinations(p.slots).length,20);});
test('메가 두 마리 파티는 16조합',()=>{const p=initial();const c=combinations(p.slots);assert.equal(c.length,16);assert(c.every(x=>!(x.includes(0)&&x.includes(1))));});
test('전기 땅 무효와 얼음 비행드래곤 4배',()=>{assert.equal(multiplier('Electric',['Ground']),0);assert.equal(multiplier('Ice',['Dragon','Flying']),4);});
test('부유와 두꺼운지방 반영',()=>{assert.equal(multiplier('Ground',['Dragon'],'부유'),0);assert.equal(multiplier('Fire',['Ice','Ground'],'두꺼운지방'),1);});
test('스카이스킨은 노말 공격을 비행으로',()=>assert.equal(selectedMoves(sample('mega-salamence'))[0].type,'Flying'));
test('기술 배치로 물리→특수 변경',()=>{const s=sample('mega-salamence');assert.equal(profile(s).role,'물리형');s.moves=['하이퍼보이스','용성군','화염방사','날개쉬기'];s.nature='조심';s.ev=[2,0,0,32,0,32];assert.equal(profile(s).role,'특수형');});
test('기존 EV 각252 / 총510 검증',()=>{const s=sample('mamoswine');s.mode='legacy';s.ev=[4,252,0,0,0,252];assert(!errors(s).some(x=>x.includes('배분')));s.ev[0]=8;assert(errors(s).some(x=>x.includes('510')));s.ev=[0,253,0,0,0,0];assert(errors(s).some(x=>x.includes('252')));});
test('챔피언스 32 / 66 검증',()=>{const s=sample('mamoswine');s.ev[0]=3;assert(errors(s).some(x=>x.includes('66')));});
test('미검증 샘플을 채우지 않는다',()=>{const p=dex.find(x=>!samples[x.species]);assert.deepEqual(sample(p.id).moves,['','','','']);assert(errors(sample(p.id)).length>0);});
test('기술 중복 및 습득 목록 검증',()=>{const s=sample('mamoswine');s.moves=['지진','지진','하이퍼보이스',''];assert(errors(s).some(x=>x.includes('중복')));assert(errors(s).some(x=>x.includes('습득')));});
test('교체 전후 계산 갱신',()=>{const p=initial(),next=replace(p,5,'garchomp');assert.notDeepEqual(analyze(p),analyze(next));});
test('6단계 서브 에이스 방향 갱신',()=>{const p=initial();const before=analyze(p).steps[4].why;p.slots[0].moves=['하이퍼보이스','용성군','화염방사','날개쉬기'];assert.notEqual(analyze(p).steps[4].why,before);});
test('자동 저장 JSON 복원 검증',()=>assert(validateParty(JSON.parse(JSON.stringify(initial())))));
test('손상된 저장 상태 거부',()=>assert(!validateParty({slots:[],ace:100})));
test('AI 입력은 현재 배치와 계산 출처 포함',()=>{const p=initial();p.slots[0].nature='조심';const v=advicePayload(p);assert.equal(v.party[0].nature,'조심');assert.equal(v.party[0].moveDetails.length,4);assert.equal(v.analysis.steps.length,6);assert(v.sources.length>0);});
const request=p=>new Request('https://example.com/api/advice',{method:'POST',headers:{'Content-Type':'application/json',origin:'https://example.com'},body:JSON.stringify({party:p})});
test('AI 미설정은 명확한503',async()=>{const r=await handleAdvice(request(initial()),{});assert.equal(r.status,503);assert.match((await r.json()).error,/아직 연결/);});
test('AI 실패 안전 처리',async()=>{const r=await handleAdvice(request(initial()),{key:'fake',model:'test'},async()=>new Response('',{status:429}));assert.equal(r.status,502);assert(!JSON.stringify(await r.json()).includes('fake'));});
test('AI 요청 실제 현재 상태 전달·응답 파싱 (mock)',async()=>{let payload;const r=await handleAdvice(request(initial()),{key:'fake',model:'test'},async(_,o)=>{payload=JSON.parse(o.body);return Response.json({output:[{content:[{type:'output_text',text:'테스트 응답'}]}]});});assert.equal((await r.json()).text,'테스트 응답');assert.equal(JSON.parse(payload.input).party.length,6);assert.equal(payload.store,false);});
test('AI 잘못된 입력과 외부 origin 차단',async()=>{assert.equal((await handleAdvice(request({}),{})).status,400);const r=new Request('https://example.com/api/advice',{method:'POST',headers:{origin:'https://evil.example'},body:'{}'});assert.equal((await handleAdvice(r,{})).status,403);});
