import roster from './roster.json';
import megas from './megas.json';
export const checked = '2026-09-15';
export const sources = [
 {name:'Pokémon Champions 공식',url:'https://champions.pokemon.com/',scope:'공식 게임 정보',date:checked},
 {name:'Pokémon Zone 싱글 순위',url:'https://www.pokemon-zone.com/champions/ranked-seasons/singles/tier-list/',scope:'M-C · 시즌 6 · 종별 순위 (9월 14일)',date:checked},
 {name:'OP.GG 챔피언스',url:'https://op.gg/ko/pokemon-champions/pokedex',scope:'개별 도감의 싱글 기술·특성·물건·배분 통계',date:checked},
 {name:'Pokémon Zone 메가폼',url:'https://www.pokemon-zone.com/champions/tier-list-mega/?include_drops=1&sort=popular',scope:'관측된 메가폼·타입만 사용. 더블 사용률은 평가에서 제외',date:checked}
];
export const types = ['Normal','Fire','Water','Electric','Grass','Ice','Fighting','Poison','Ground','Flying','Psychic','Bug','Rock','Ghost','Dragon','Dark','Steel','Fairy'];
export const typeKo = Object.fromEntries(types.map((t,i)=>[t,['노말','불꽃','물','전기','풀','얼음','격투','독','땅','비행','에스퍼','벌레','바위','고스트','드래곤','악','강철','페어리'][i]]));
const names:Record<string,string> = Object.fromEntries(`Salamence:보만다|Garchomp:한카리아스|Primarina:누리레느|Golisopod:갑주무사|Hippowdon:하마돈|Baxcalibur:드닐레이브|Lucario:루카리오|Gholdengo:타부자고|Archaludon:브리두라스|Aegislash:킬가르도|Mimikyu:따라큐|Meowscarada:마스카나|Rillaboom:고릴타|Gyarados:갸라도스|Corviknight:아머까오|Glimmora:킬라플로르|Greninja:개굴닌자|Charizard:리자몽|Cinderace:에이스번|Sneasler:포푸니크|Volcarona:불카모스|Pawmot:빠르모트|Hydreigon:삼삼드래|Skeledirge:라우드본|Metagross:메타그로스|Dragonite:망나뇽|Sylveon:님피아|Delphox:마폭시|Gengar:팬텀|Kingambit:대도각참|Blaziken:번치코|Swampert:대짱이|Empoleon:엠페르트|Umbreon:블래키|Raichu:라이츄|Toxapex:더시마사리|Blastoise:거북왕|Banette:다크펫|Scizor:핫삼|Grimmsnarl:오롱털|Absol:앱솔|Bellibolt:찌리배리|Mamoswine:맘모꾸리|Ceruledge:파라블레이즈|Clefable:픽시|Pelipper:패리퍼|Armarouge:카디나르마|Venusaur:이상해꽃|Beedrill:독침붕|Pidgeot:피죤투|Alakazam:후딘|Slowbro:야도란|Kangaskhan:캥카|Pinsir:쁘사이저|Aerodactyl:프테라|Ampharos:전룡|Steelix:강철톤|Heracross:헤라크로스|Houndoom:헬가|Tyranitar:마기라스|Sceptile:나무킹|Gardevoir:가디안|Sableye:깜까미|Mawile:입치트|Aggron:보스로라|Medicham:요가램|Manectric:썬더볼트|Sharpedo:샤크니아|Camerupt:폭타|Altaria:파비코리|Glalie:얼음귀신|Lopunny:이어롭|Gallade:엘레이드|Audino:다부니|Diancie:디안시|Floette:플라엣테|Chesnaught:브리가론|Feraligatr:장크로다일|Meganium:메가니움|Emboar:염무왕|Excadrill:몰드류|Dragonair:신뇽|Drampa:할비롱|Eelektross:저리더프|Chandelure:샹델라|Malamar:칼라마네로|Barbaracle:거북손데스|Dragalge:드래캄|Hawlucha:루차불|Froslass:눈여아|Frosmoth:모스노우|Talonflame:파이어로|Starmie:아쿠스타|Victreebel:우츠보트|Scovillain:스코빌런|Glimmora:킬라플로르|Zeraora:제라오라|Skarmory:무장조|Milotic:밀로틱|Rotom:로토무|Ninetales:나인테일|Indeedee:에써르|Basculegion:대쓰여너|Dondozo:어써러셔|Tatsugiri:싸리용|Arcanine:윈디|Goodra:미끄래곤|Typhlosion:블레이범|Samurott:대검귀|Decidueye:모크나이퍼|Zoroark:조로아크`.split('|').map(x=>x.split(':')));
export function korean(en:string){let n=en;for(const [a,b] of Object.entries(names).sort((a,b)=>b[0].length-a[0].length))n=n.replace(a,b);return n.replace('Mega ','메가').replace('Alolan ','알로라 ').replace('Hisuian ','히스이 ').replace('Galarian ','가라르 ').replace('Wash ','워시').replace('Heat ','히트').replace(' (Male)',' (수컷)').replace(' (Female)',' (암컷)');}
export const slug=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/-$/,'');
export const species=(s:string)=>s.replace(/^Mega /,'').replace(/ [XYZ]$/,'').replace(/^(Alolan|Hisuian|Galarian|Paldean|Wash|Heat|Frost|Fan|Mow) /,'').replace(/ \(.*\)$/,'');
export interface Pokemon {id:string;en:string;name:string;types:string[];rank:number|null;mega:boolean;form:string;species:string}
export const dex:Pokemon[] = [...roster,...megas].map(p=>({id:slug(p.en),en:p.en,name:korean(p.en),types:p.types,rank:'rank'in p?Number(p.rank):roster.find(r=>species(r.en)===species(p.en))?.rank??null,mega:p.en.startsWith('Mega '),form:p.en.startsWith('Mega ')?(/[XYZ]$/.test(p.en)?p.en.slice(-1):'메가'):'기본',species:species(p.en)}));
export const byId=Object.fromEntries(dex.map(p=>[p.id,p]));
export interface Move {name:string;type:string;category:'물리'|'특수'|'변화';power:number;accuracy:number;priority:number;tags:string[]}
const moveRows:[string,string,Move['category'],number,number,number,string?][]=[
 ['지진','Ground','물리',100,100,0],['얼음뭉치','Ice','물리',40,100,1,'선공기'],['고드름떨구기','Ice','물리',85,90,0],['고드름침','Ice','물리',25,100,0,'연속기'],['스텔스록','Rock','변화',0,100,0,'장판 설치'],['암석봉인','Rock','물리',60,95,0,'스피드 제어'],['스톤에지','Rock','물리',100,80,0],['스톤샤워','Rock','물리',75,90,0],['탁쳐서떨구기','Dark','물리',65,100,0,'물건 제거'],
 ['이판사판태클','Normal','물리',120,100,0,'반동'],['용의춤','Dragon','변화',0,100,0,'랭크업,스피드 제어'],['날개쉬기','Flying','변화',0,100,0,'회복'],['용성군','Dragon','특수',130,90,0,'특공 하락'],['화염방사','Fire','특수',90,100,0],['하이퍼보이스','Normal','특수',90,100,0,'소리'],['불대문자','Fire','특수',110,85,0],['역린','Dragon','물리',120,100,0],['열불내기','Fire','물리',75,100,0],
 ['아이언헤드','Steel','물리',80,100,0],['만나자마자','Bug','물리',100,100,2,'선공기,첫 턴 한정'],['기습','Dark','물리',70,100,1,'선공기,조건부'],['유턴','Bug','물리',70,100,0,'대면 조작'],['드릴라이너','Ground','물리',80,95,0],['흡혈','Bug','물리',80,100,0,'회복'],['인파이트','Fighting','물리',120,100,0],['칼춤','Normal','변화',0,100,0,'랭크업'],['아쿠아제트','Water','물리',40,100,1,'선공기'],['벌크업','Fighting','변화',0,100,0,'랭크업'],
 ['문포스','Fairy','특수',95,100,0],['물거품아리아','Water','특수',90,100,0,'소리'],['앙코르','Normal','변화',0,100,0,'기점 마련'],['명상','Psychic','변화',0,100,0,'랭크업'],['퀵턴','Water','물리',60,100,0,'대면 조작'],['잠자기','Psychic','변화',0,100,0,'회복'],['파도타기','Water','특수',90,100,0],['냉동빔','Ice','특수',90,100,0],['미스트필드','Fairy','변화',0,100,0,'필드'],['드래곤테일','Dragon','물리',60,90,-6,'강제 교체'],
 ['바디프레스','Fighting','물리',80,100,0,'방어 참조'],['철벽','Steel','변화',0,100,0,'랭크업'],['브레이브버드','Flying','물리',120,100,0,'반동'],['도발','Dark','변화',0,100,0,'기점 마련'],['안개제거','Flying','변화',0,100,0,'장판 제거'],['섀도볼','Ghost','특수',80,100,0],['오물웨이브','Poison','특수',95,100,0],['길동무','Ghost','변화',0,100,0,'교환'],['방어','Normal','변화',0,100,4],['기합구슬','Fighting','특수',120,70,0],['오물폭탄','Poison','특수',90,100,0],['얼어붙은바람','Ice','특수',55,95,0,'스피드 제어'],['병상첨병','Ghost','특수',65,100,0,'상태이상 연계']
];
export const moves:Record<string,Move>=Object.fromEntries(moveRows.map(([name,type,category,power,accuracy,priority,tags])=>[name,{name,type,category,power,accuracy,priority,tags:tags?.split(',')??[]}]));
export interface Sample {moves:string[];rates:number[];ability:string;abilities:string[];item:string;nature:string;ev:number[];evRate:number;alternatives:string[];stats:number[];itemRate:number;abilityRate:number;natureRate:number}
export const samples:Record<string,Sample>={
 Salamence:{moves:['이판사판태클','용의춤','지진','날개쉬기'],rates:[75.3,73.6,70.2,66.2],ability:'위협',abilities:['위협','자기과신'],item:'보만다나이트',nature:'고집',ev:[1,32,1,0,0,32],evRate:13.2,alternatives:['용성군','화염방사','하이퍼보이스','불대문자','역린','열불내기'],stats:[95,135,80,110,80,100],itemRate:97.8,abilityRate:99.3,natureRate:51.8},
 Golisopod:{moves:['아이언헤드','만나자마자','기습','유턴'],rates:[77.4,74.5,55.3,45.2],ability:'위기회피',abilities:['위기회피'],item:'갑주무사나이트',nature:'고집',ev:[32,32,0,0,2,0],evRate:25.2,alternatives:['드릴라이너','흡혈','인파이트','칼춤','아쿠아제트','벌크업'],stats:[75,125,140,60,90,40],itemRate:98.7,abilityRate:100,natureRate:81.6},
 Mamoswine:{moves:['지진','얼음뭉치','고드름떨구기','고드름침'],rates:[99.1,97.8,44.4,43.6],ability:'둔감',abilities:['둔감','두꺼운지방','눈숨기'],item:'기합의띠',nature:'고집',ev:[2,32,0,0,0,32],evRate:51.6,alternatives:['스텔스록','암석봉인','스톤에지','스톤샤워','탁쳐서떨구기'],stats:[110,130,80,70,60,80],itemRate:85.4,abilityRate:54.5,natureRate:83.6},
 Primarina:{moves:['문포스','물거품아리아','아쿠아제트','앙코르'],rates:[98.2,92.6,67.8,47.5],ability:'급류',abilities:['급류','촉촉보이스'],item:'자뭉열매',nature:'조심',ev:[32,0,20,14,0,0],evRate:8.4,alternatives:['명상','퀵턴','잠자기','파도타기','냉동빔','미스트필드'],stats:[80,74,74,126,116,60],itemRate:40.4,abilityRate:96.4,natureRate:70.2},
 Corviknight:{moves:['날개쉬기','유턴','바디프레스','철벽'],rates:[99.2,64.6,62.8,59.2],ability:'프레셔',abilities:['프레셔','미러아머','긴장감'],item:'울퉁불퉁멧',nature:'장난꾸러기',ev:[32,0,32,0,2,0],evRate:44.4,alternatives:['브레이브버드','벌크업','아이언헤드','도발','안개제거'],stats:[98,87,105,53,85,67],itemRate:65.9,abilityRate:62.2,natureRate:67},
 Gengar:{moves:['섀도볼','오물웨이브','길동무','방어'],rates:[86.2,68.3,62.6,48.4],ability:'저주받은바디',abilities:['저주받은바디'],item:'팬텀나이트',nature:'겁쟁이',ev:[2,0,0,32,0,32],evRate:40.2,alternatives:['기합구슬','오물폭탄','얼어붙은바람','병상첨병'],stats:[60,65,60,130,75,110],itemRate:75.5,abilityRate:100,natureRate:85.6},
 Garchomp:{moves:['지진','스텔스록','용성군','드래곤테일'],rates:[67.8,40,29.3,26.8],ability:'까칠한피부',abilities:['까칠한피부','모래숨기'],item:'한카리아스나이트Z',nature:'명랑',ev:[2,32,0,0,0,32],evRate:27.7,alternatives:[],stats:[108,130,95,80,85,102],itemRate:34.5,abilityRate:99.2,natureRate:24.3}
};
export const megaAbilities:Record<string,string>={'mega-salamence':'스카이스킨','mega-golisopod':'단단한발톱','mega-gengar':'그림자밟기','mega-garchomp-z':'부유'};
export const natures:Record<string,[number,number]>={'무보정':[-1,-1],'고집':[1,3],'조심':[3,1],'명랑':[5,3],'겁쟁이':[5,1],'장난꾸러기':[2,3],'대담':[2,1],'차분':[4,1],'신중':[4,3],'용감':[1,5],'냉정':[3,5],'무사태평':[2,5],'건방':[4,5]};
export const items=['없음','기합의띠','자뭉열매','먹다남은음식','울퉁불퉁멧','구애스카프','구애안경','구애머리띠','생명의구슬','리샘열매'];
export const statNames=['HP','공격','방어','특수공격','특수방어','스피드'];
