import {byId,dex,moves,samples,megaAbilities,natures,types,korean,sources,slug} from './data';
export interface Slot {id:string;ability:string;item:string;nature:string;ev:number[];mode:'champions'|'legacy';moves:string[];locked:boolean}
export interface Party {slots:Slot[];ace:number}
export function sample(id:string):Slot {const p=byId[id];const s=samples[p.species];return {id,ability:p.mega?megaAbilities[id]??'':s?.ability??'',item:p.mega?s?.item??'':s?.item.includes('나이트')?'없음':s?.item??'없음',nature:s?.nature??'무보정',ev:s?[...s.ev]:[0,0,0,0,0,0],mode:'champions',moves:s?[...s.moves]:['','','',''],locked:false};}
export const initial=():Party=>({ace:0,slots:['mega-salamence','mega-golisopod','mamoswine','primarina','corviknight','gengar'].map(sample)});
// Standard type chart: attacking type -> [super-effective, resisted, immune].
const chart:Record<string,string[]>= {Normal:['','Rock Steel','Ghost'],Fire:['Grass Ice Bug Steel','Fire Water Rock Dragon',''],Water:['Fire Ground Rock','Water Grass Dragon',''],Electric:['Water Flying','Electric Grass Dragon','Ground'],Grass:['Water Ground Rock','Fire Grass Poison Flying Bug Dragon Steel',''],Ice:['Grass Ground Flying Dragon','Fire Water Ice Steel',''],Fighting:['Normal Ice Rock Dark Steel','Poison Flying Psychic Bug Fairy','Ghost'],Poison:['Grass Fairy','Poison Ground Rock Ghost','Steel'],Ground:['Fire Electric Poison Rock Steel','Grass Bug','Flying'],Flying:['Grass Fighting Bug','Electric Rock Steel',''],Psychic:['Fighting Poison','Psychic Steel','Dark'],Bug:['Grass Psychic Dark','Fire Fighting Poison Flying Ghost Steel Fairy',''],Rock:['Fire Ice Flying Bug','Fighting Ground Steel',''],Ghost:['Psychic Ghost','Dark','Normal'],Dragon:['Dragon','Steel','Fairy'],Dark:['Psychic Ghost','Fighting Dark Fairy',''],Steel:['Ice Rock Fairy','Fire Water Electric Steel',''],Fairy:['Fighting Dragon Dark','Fire Poison Steel','']};
export function multiplier(attack:string,defense:string[],ability=''){if((ability==='부유'&&attack==='Ground')||(['축전','피뢰침','전기엔진'].includes(ability)&&attack==='Electric')||(['저수','마중물','건조피부'].includes(ability)&&attack==='Water')||(ability==='타오르는불꽃'&&attack==='Fire'))return 0;let n=defense.reduce((v,t)=>v*(chart[attack]?.[2].split(' ').includes(t)?0:chart[attack]?.[0].split(' ').includes(t)?2:chart[attack]?.[1].split(' ').includes(t)?.5:1),1);if(ability==='두꺼운지방'&&['Fire','Ice'].includes(attack))n*=.5;return n;}
export function selectedMoves(s:Slot){return s.moves.map(n=>moves[n]).filter(Boolean).map(m=>({...m,type:s.ability==='스카이스킨'&&m.type==='Normal'&&m.category!=='변화'?'Flying':s.ability==='촉촉보이스'&&m.tags.includes('소리')?'Water':m.type}));}
export function legalMoves(s:Slot){const a=samples[byId[s.id].species];return a?[...a.moves,...a.alternatives]:[];}
export function errors(s:Slot){const e:string[]=[];const p=byId[s.id];if(!p)return ['알 수 없는 포켓몬'];const cap=s.mode==='legacy'?252:32,total=s.mode==='legacy'?510:66;if(s.ev.length!==6||s.ev.some(v=>!Number.isInteger(v)||v<0||v>cap)||s.ev.reduce((a,b)=>a+b,0)>total)e.push(`능력치 배분은 각 ${cap} / 합계 ${total} 이내여야 합니다.`);if(s.moves.filter(Boolean).length!==4)e.push('기술 4개 자료가 필요합니다.');if(new Set(s.moves.filter(Boolean)).size!==s.moves.filter(Boolean).length)e.push('같은 기술을 중복 채용할 수 없습니다.');if(s.moves.some(n=>n&&!legalMoves(s).includes(n)))e.push('검증된 습득 기술 목록 밖의 기술입니다.');if(p.mega&&!megaAbilities[s.id])e.push('폼별 특성·메가스톤 검증 자료 없음');if(!s.ability)e.push('특성 자료 없음');if(p.mega&&samples[p.species]&&s.item!==samples[p.species].item)e.push('메가스톤과 폼을 확인하세요.');return e;}
function investment(s:Slot,i:number){return s.ev[i]/(s.mode==='legacy'?252:32);}
function natureFactor(s:Slot,i:number){const n=natures[s.nature]??[-1,-1];return n[0]===i?1.1:n[1]===i?.9:1;}
export function profile(s:Slot){const ms=selectedMoves(s),base=samples[byId[s.id].species]?.stats;const physical=ms.filter(m=>m.category==='물리').reduce((a,m)=>a+m.power*(m.name==='바디프레스'?(base?.[2]??80):(base?.[1]??80))*(1+investment(s,m.name==='바디프레스'?2:1)*.3)*natureFactor(s,m.name==='바디프레스'?2:1)*(m.priority>0?.45:1),0);const special=ms.filter(m=>m.category==='특수').reduce((a,m)=>a+m.power*(base?.[3]??80)*(1+investment(s,3)*.3)*natureFactor(s,3),0);const role=!physical&&!special?'보조형':physical>special*2?'물리형':special>physical*2?'특수형':'쌍두형';const tags=[...new Set(ms.flatMap(m=>m.tags))];const issues:string[]=[];if(!ms.some(m=>m.power>=80&&byId[s.id].types.includes(m.type)))issues.push('고위력 자속기 없음 (보조형은 의도 확인)');if(role==='물리형'&&investment(s,3)>.5)issues.push('물리 주력과 특수공격 배분 불일치');if(role==='특수형'&&investment(s,1)>.5)issues.push('특수 주력과 공격 배분 불일치');if((role==='특수형'&&natures[s.nature]?.[1]===3)||(role==='물리형'&&natures[s.nature]?.[1]===1))issues.push('성격이 주력 공격 능력치를 낮춥니다.');if(ms.filter(m=>m.power>0&&m.accuracy<90).length>=2)issues.push('낮은 명중률 기술에 대한 의존');if(s.item.startsWith('구애')&&ms.some(m=>m.category==='변화'))issues.push('구애 도구의 기술 고정과 변화기 운용 주의');if(ms.filter(m=>m.power>0).length>1&&new Set(ms.filter(m=>m.power>0).map(m=>m.type)).size===1)issues.push('공격 타입 중복');return {role,tags,issues,physical:Math.round(physical),special:Math.round(special),speedIndex:base?Math.round(base[5]*(1+investment(s,5)*.3)*natureFactor(s,5)*(s.item==='구애스카프'?1.5:1)):null};}
export function combinations(slots:Slot[]){const all:number[][]=[];for(let a=0;a<slots.length;a++)for(let b=a+1;b<slots.length;b++)for(let c=b+1;c<slots.length;c++)if([a,b,c].filter(i=>byId[slots[i].id].mega).length<=1)all.push([a,b,c]);return all;}
export function validateParty(p:unknown):p is Party {if(!p||typeof p!=='object')return false;const v=p as Party;return Number.isInteger(v.ace)&&v.ace>=0&&v.ace<6&&Array.isArray(v.slots)&&v.slots.length===6&&v.slots.every(s=>s&&byId[s.id]&&typeof s.ability==='string'&&s.ability.length<60&&typeof s.item==='string'&&s.item.length<60&&s.nature in natures&&['legacy','champions'].includes(s.mode)&&typeof s.locked==='boolean'&&Array.isArray(s.ev)&&s.ev.length===6&&s.ev.every(n=>Number.isFinite(n)&&n>=0&&n<=510)&&Array.isArray(s.moves)&&s.moves.length===4&&s.moves.every(n=>typeof n==='string'&&(!n||Boolean(moves[n]))))&&new Set(v.slots.map(s=>byId[s.id].species)).size===6;}
export function replace(p:Party,index:number,id:string){if(!byId[id]||index<0||index>5)throw Error('포켓몬 또는 슬롯이 올바르지 않습니다.');if(p.slots[index].locked)throw Error('고정한 슬롯입니다. 고정을 해제하세요.');if(p.slots.some((s,i)=>i!==index&&byId[s.id].species===byId[id].species))throw Error('동일 종의 다른 폼은 함께 넣을 수 없습니다.');return {...p,slots:p.slots.map((s,i)=>i===index?sample(id):s)};}
export function analyze(p:Party,indices?:number[]){const ss=indices?indices.map(i=>p.slots[i]):p.slots;const profiles=ss.map(profile),tags=[...new Set(profiles.flatMap(p=>p.tags))];const offense=types.map(t=>({type:t,best:Math.max(0,...ss.flatMap(s=>selectedMoves(s).filter(m=>m.power>0).map(m=>multiplier(m.type,[t]))))}));const defense=types.map(t=>{const factors=ss.map(s=>multiplier(t,byId[s.id].types,s.ability));return {type:t,weak:factors.filter(v=>v>1).length,resist:factors.filter(v=>v>0&&v<1).length,immune:factors.filter(v=>v===0).length,factors,switches:ss.filter((_,i)=>factors[i]<1).map(s=>byId[s.id].name)};});
 const threats=dex.filter(x=>!x.mega&&x.rank&&x.rank<=13).map(enemy=>{const attacks=ss.flatMap(s=>selectedMoves(s).filter(m=>m.power>0).map(m=>({name:byId[s.id].name,move:m.name,factor:multiplier(m.type,enemy.types)})));const best=Math.max(0,...attacks.map(a=>a.factor));return {name:enemy.name,id:enemy.id,types:enemy.types,best,answers:attacks.filter(a=>a.factor>=2),warning:best<2?'약점 타격 없음':'약점 타격 가능 · 승리 보장 아님'};});
 const parts=[{name:'공격 범위',weight:25,value:Math.round(offense.filter(t=>t.best>=2).length/18*100)},{name:'교체 상성',weight:25,value:Math.round(defense.filter(t=>t.resist+t.immune>0).length/18*100)},{name:'공격 성향',weight:15,value:profiles.some(x=>x.role==='물리형')&&profiles.some(x=>x.role==='특수형')?100:profiles.some(x=>x.role==='쌍두형')?60:25},{name:'유틸리티',weight:15,value:Math.round(['대면 조작','선공기','장판 설치','장판 제거','회복','스피드 제어'].filter(t=>tags.includes(t)).length/6*100)},{name:'메타 타입 타격',weight:15,value:Math.round(threats.filter(t=>t.best>=2).length/Math.max(1,threats.length)*100)},{name:'배치 일관성',weight:5,value:Math.max(0,100-profiles.reduce((a,b)=>a+b.issues.length,0)*15)}];
 const score=Math.round(parts.reduce((v,s)=>v+s.value*s.weight/100,0));const ace=p.slots[p.ace],ap=profile(ace),opposite=ap.role==='특수형'?'물리형':'특수형';const supporters=ss.filter(s=>profile(s).tags.some(t=>['대면 조작','기점 마련','장판 설치'].includes(t)));const counters=types.filter(t=>multiplier(t,byId[ace.id].types,ace.ability)>1);const checks=ss.filter(s=>s!==ace&&counters.some(t=>multiplier(t,byId[s.id].types,s.ability)<1));const sub=ss.filter(s=>s!==ace&&profile(s).role===opposite);const steps=[
 {title:'메인 에이스',owners:[ace],ok:selectedMoves(ace).some(m=>m.power>=80),why:`${byId[ace.id].name} · ${ap.role}. 주력기와 성격·배분의 일치를 확인하세요.`,advice:ap.issues.join(' / ')||'선출에서 에이스의 안전한 진입 시점을 확보하세요.'},
 {title:'서포터',owners:supporters,ok:supporters.length>0,why:'대면 조작·기점 마련·장판 기술의 실제 채용 여부',advice:'유턴·퀵턴·앙코르 또는 장판으로 에이스 진입을 보조하세요.'},
 {title:'카운터 상정',owners:[ace],ok:false,why:`타입 약점: ${counters.join(', ')}. 상대 배치·대미지까지는 미검증`,advice:'메타 타격 표는 천적 확정 판정이 아닙니다. 상대 메가폼과 기술을 별도로 확인하세요.'},
 {title:'카운터 견제몬',owners:checks,ok:checks.length>0,why:'에이스 약점 중 하나 이상을 반감·무효로 받는 멤버',advice:'반감 교체 후보도 상대 서브 웨폰과 누적 피해에 따라 안전하지 않을 수 있습니다.'},
 {title:'서브 에이스',owners:sub,ok:sub.length>0,why:`메인의 반대 성향인 ${opposite} 공격원`,advice:`${opposite} 주력기를 가진 멤버를 확보해 에이스 미선출 플랜을 만드세요.`},
 {title:'파티 보완',owners:ss.filter(s=>profile(s).tags.length>0),ok:['대면 조작','선공기','스피드 제어'].every(t=>tags.includes(t)),why:`확인된 역할: ${tags.join(', ')||'없음'}`,advice:`보완할 유틸리티: ${['대면 조작','선공기','스피드 제어','장판 설치','장판 제거'].filter(t=>!tags.includes(t)).join(', ')||'핵심 항목 확보'}`}
 ].map((s,i)=>({...s,status:s.ok?'충족':s.owners.length?'부분 충족':'미충족',owners:s.owners.map(x=>byId[x.id].name),number:i+1}));
 return {score,parts,offense,defense,profiles,tags,threats,steps,issues:ss.flatMap(s=>[...errors(s),...profile(s).issues].map(e=>`${byId[s.id].name}: ${e}`)),complete:ss.every(s=>errors(s).length===0),physical:profiles.filter(p=>p.role==='물리형').length,special:profiles.filter(p=>p.role==='특수형').length,combinationCount:combinations(p.slots).length};
}
export function rankedSelections(p:Party){return combinations(p.slots).map(indices=>({indices,score:analyze(p,indices).score})).sort((a,b)=>b.score-a.score);}
export function advicePayload(p:Party){return {party:p.slots.map(s=>({...s,pokemon:byId[s.id],moveDetails:selectedMoves(s),profile:profile(s),source:`https://op.gg/ko/pokemon-champions/pokedex/${slug(byId[s.id].species)}`})),mainAce:p.ace,analysis:analyze(p),selections:rankedSelections(p),sources,limitations:['점수는 규칙 기반 휴리스틱이며 승률이 아닙니다.','상대 배치·정밀 대미지·공개 파티 유사도는 미검증','7종의 종별 통계 샘플만 확인. 그 외 샘플은 자료 없음','상위 4개 기술은 공동 사용 조합이 아닙니다.']};}
